###
POST http://localhost:8083/api/netypes
Content-Type: application/json

{
    "name":"2",
    "description":"desc",
    "namedEntityTypeParent":1,
    "textTags":[],
    "taskSets":[]
}

###
GET http://localhost:8083/api/netypes/2
###
PUT http://localhost:8083/api/netypes/2
Content-Type: application/json

{
    "name":"Zmiana",
    "description":"new",
    "namedEntityTypeParent":1,
    "textTags":[],
    "taskSets":[2]
}

###

DELETE http://localhost:8083/api/netypes/1
###
GET http://localhost:8083/api/netypes/2

###