###
POST http://localhost:8083/api/netypes
Content-Type: application/json

{
    "name":"1",
    "description":"desc",
    "namedEntityTypeParent":1,
    "textTags":[],
    "taskSets":[]
}

###
GET http://localhost:8083/api/netypes/1
###
GET http://localhost:8083/api/task_sets/1
###
PUT http://localhost:8083/api/netypes/2
Content-Type: application/json

{
    "name":"Zmiana",
    "description":"new",
    "namedEntityTypeParent":1,
    "textTags":[],
    "taskSets":[2]
}

###

DELETE http://localhost:8083/api/netypes/1
###
GET http://localhost:8083/api/netypes/1
###
POST http://localhost:8083/api/tags
Content-Type: application/json

{
    "namedEntityTypes":[]
}
###

POST http://localhost:8083/api/task_sets
Content-Type: application/json

{
    "namedEntityTypes":[]
}