###
POST http://localhost:8084/api/texts/1/entities
Content-Type: application/json

{
    "indexStart":1,
    "indexEnd":2,
    "text_id":1,
    "kb_link":"link",
    "type_id":1
}
###
POST http://localhost:8084/api/texts
Content-Type: application/json

{
}
###
POST http://localhost:8084/api/types
Content-Type: application/json

{
}
###
GET http://localhost:8084/api/texts/1

###
GET http://localhost:8084/api/texts/1/entities/1
###

DELETE http://localhost:8084/api/texts/1
###
DELETE http://localhost:8084/api/texts/1/entities/1

###
PUT http://localhost:8084/api/texts/1/entities/1
Content-Type: application/json

{
    "indexStart":3,
    "indexEnd":5,
    "text_id":1,
    "kb_link":"nowy link",
    "type_id":1
}

###