###
POST http://localhost:8082/api/tags
Content-Type: application/json

{
    "name":"TAG4",
    "description":"desc1",
    "namedEntityTypes":[2],
    "texts":[]
}
###

GET http://localhost:8082/api/tags/1
###
GET http://localhost:8082/api/tags
###

PUT http://localhost:8082/api/tags/1
Content-Type: application/json

{
    "name":"TAG2",
    "description":"DESCRIPTION2",
    "namedEntityTypes":[1],
    "texts":[]
}
###

DELETE http://localhost:8082/api/tags/1
###
GET http://localhost:8082/api/tags
###
GET http://localhost:8082/api/tags/1

###
GET http://localhost:8082/api/netypes/1
