###

POST http://localhost:8091/api/response/4/raport
Content-Type: application/json

{
    "content": "AAAAAAAAAAAAAAAAAAAAAA"
}
###
POST http://localhost:8091/api/raport
Content-Type: application/json

{
    "content": "BBBBBBBBBBBBBBBBBBBBB"
}
###
PUT http://localhost:8091/api/response/4/raport/1
Content-Type: application/json

{
    "content": "CCCCCCCCCCCCCCCCCCC"
}

###
GET http://localhost:8091/api/response/4/raport
###
GET http://localhost:8091/api/raport/2
###